kind = "web"
previewPath = "/"
title = "WorldAlert"
version = "1.0.0"
id = "artifacts/world-alert"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19858

[services.development]
run = "pnpm --filter @workspace/world-alert run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/world-alert", "run", "build" ]
publicDir = "artifacts/world-alert/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19858"
BASE_PATH = "/"
